OOP school library: decorate a class
Feliverse/OOP-school-library pull request #3
Opened 2023-04-19 23:30 UTC by Feliverse

### Project requirements

- Check the usage of [Decorator pattern in Ruby](https://refactoring.guru/design-patterns/decorator/ruby/example#example-0)
- Think about how you can use two decorators in order to capitalize and trim people's names.
- In the following steps you will get instructions for implementing the Decorator design pattern for this case.

**Interface**

- Create a class Nameable.
- Implement a method called correct_name that will raise a NotImplementedError.
- Turn your Person class to Nameable
- Make sure that your Person class inherits from Nameable
- Make sure that this class has a method correct_name implemented. It should simply return the name attribute.

**Prepare base Decorator**

- Make sure that it inherits from Nameable.
- In the constructor assign a nameable object from params to an instance variable.
- Implement the correct_name method that returns the result of the correct_name method of the @nameable.

**Prepare CapitalizeDecorator and TrimmerDecorator**

- For the CapitalizeDecorator:
- Create a class that inherits from the base Decorator class.
- Implement a method correct_name that capitalizes the output of @nameable.correct_name.
- For the TrimmerDecorator:
- Create a class that inherits from the base Decorator class.
- Implement a method correct_name that makes sure that the output of @nameable.correct_name has a maximum of 10 characters. If it's longer it should trim the word.

2023-04-19 23:54 UTC, rotimiazeez requested changes
# Hi @Feliverse 👍🏽,
## Good job so far!
### To Highlight 👇🏽
- Class well decorated 👏🏽
- No Linter error ✔️ 
- Good PR description 👍🏽 
- Good commit message(s) 😉
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR WORDS>


## Suggested changes
### Please ensure your README is formatted as seen [here](https://github.com/microverseinc/readme-template) to make it look more professional. 😉
### Please remove the Microverse logo from your README file. You can add a personal logo or leave it blank if you don't have any 👍🏽
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you consider them as they can improve your code._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag (@rotimiazeez) me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

2023-04-20 13:01 UTC, TadesseDev approved these changes
### Hi @Feliverse 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy (1)](https://user-images.githubusercontent.com/69077061/212969210-69f495ba-f2fb-4559-a222-d1507310d6fb.gif)



## Highlights
 - [x] Good job making the changes requested by the previous code reviewer. ✅
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 13:01 UTC, TadesseDev commented on nameable.rb
> +  end
- [Optional] It would be wise to have a custom message next to the `raise NotImplementedError`. something like `raise NotImplementedError, "#{self.class} has not implemented method '#{__method__}'"`.

2023-04-20 13:12 UTC, Feliverse commented on nameable.rb
> +  end
Thank you, 
It's a nice suggestion, I will implement

2023-04-20 13:15 UTC, merged